#!/bin/ansible-playbook
# code: language=ansible
- name: Installing Python3 and additional libs
  hosts: all
  become: yes
  vars:
  - ansible_user: "vagrant"
  tasks:
  - name: Installing python3, python3-pip and libs
    ansible.builtin.apt:
      pkg:
        - python3
        - python3-django
        - python3-pip
        - python3-psycopg2
      state: present
      update_cache: true